### ISSUE TITLE
[GAT-MEW002-14][Windows][IE 11]  Avatar of user is not displayed

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#10]
*Issue No*: 14
*Device*: Apple iPhone 6S, Windows 10
*Web Browser*: IE 11

*Affected Component(s)*:
* Admin dashboard

----

*Bug Description*:
Actual results
The avatar of user is not displayed, only 'x' button is displayed

Expected results
Can see the avatar of user

----

*Credentials*: test_adm15

----

*Reproduction Steps*:
Go to http://stage.millennialesports.gg/
Log in with credentials and observe

*Attached Files*:
https://tracker-production.gatserver.com/video_files/1a574c9759dc26745ff9f4485a5b47892c862568f25a7b0e3d9d6a0895e90461d0080cc311aea253e97e147a72d1d4a2

**Comment by ChalkyBrush** [comment]
I made these admin accounts through console commands and never properly attached an avatar, so it's a broken link. Wouldn't happen on production
