### ISSUE TITLE
[GAT-MEW002-34][Windows][Google Chrome Version 64.0.3282.167] Cannot add new account transaction in Admin Console

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#27]
*Issue No*: 34
*Device*: Samsung Galaxy S6, Windows 10
*Web Browser*: Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)

*Affected Component(s)*:
* Admin console

----

*Bug Description*:
Actual results
When you try to add a new account transaction, you get an error "something went terribly wrong: 500 error" and you cannot add the new account transaction.

Expected results
You should be able to add a new account transaction and there should not be an error.

----

*Credentials*: test_adm25

----

*Reproduction Steps*:
Log in as admin test_adm25
Click Account Transactions
Click Add New
Enter the details for the account transaction
Click Save
See error

*Attached Files*:
https://tracker-production.gatserver.com/video_files/af49de6a995d0d3ea307ed516c0f24a85a71c53745e840e8162e0115ea70daf9bc388be1dc01251ffed1127c5efda4e8

**Comment by ChalkyBrush** [comment]
fixed
