### ISSUE TITLE
[GAT-MEW002-4][Windows][Chrome 64] Error is showing when user clicks on ""Forum" from bottom of the page

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#3]
*Issue No*: 4
*Device*: Huawei P9, Windows 10
*Web Browser*: Chrome 64

*Affected Component(s)*:
* Admin console

----

*Bug Description*:
Actual results
When user clicks on "Forum" from footer, a page is loading with 404 error message 

Expected results
Clicking on  "Forum" from the bottom of the page should take the user to the forum page.

----

*Credentials*: test_adm7

----

*Reproduction Steps*:
Browse to "http://stage.millennialesports.gg
Login as admin
Scroll down to bottom of the page
Click on "Forum"
Observe

*Attached Files*:
https://tracker-production.gatserver.com/video_files/b971daa912a699ea3a6ac8ba453a6dd39f7d2f6a13d2d93da8245b1addff34bec27b6b78968a8f46c8e28cd61cf9e693

**Comment by ChalkyBrush** [comment]
Solved,
Forums were removed with last large update, so it now links to discord
