### ISSUE TITLE
[GAT-MEW002-47][Windows][Firefox 58.0.2] The file is not attached to the Message when admin wants to reply to a support ticket.

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#33]
*Issue No*: 47
*Device*: Apple iPhone 6S, Windows 10
*Web Browser*: Firefox 58.0.2

*Affected Component(s)*:
* Admin dashboard

----

*Bug Description*:
Actual results
In the support ticket, Click on 'Browse' button, select a file, then nothing happens

Expected results
In the support ticket, User can attach the file successfully without any error

----

*Credentials*: test_adm15

----

*Reproduction Steps*:
Go to http://stage.millennialesports.gg/
Log in with credentials
Click on 'Support tickets'
Open a ticket
Scroll down and click on 'Browse' button
Select a file and observe

*Attached Files*:
https://tracker-production.gatserver.com/video_files/91c8923771438ed6754b09c4b8262fa015e3800130199eadb7f88f70502be0f83603f0ade85103005893ee984f4fe8d6

**Comment by ChalkyBrush** [comment]
#36
