### ISSUE TITLE
[GAT-MEW002-51][Windows][Chrome 64.0] User is unable to create new support ticket, no feedback received when clicking on Create Ticket.

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#35]
*Issue No*: 51
*Device*: Lenovo C2 Power, Windows 10
*Web Browser*: Chrome 64.0

*Affected Component(s)*:
* Regular user

----

*Bug Description*:
Actual results
There was no validation message to show that ticket has been created successfully and the new ticket was not seen on the list of existing tickets 

Expected results
The User should be able to create new support ticket successfully and the new ticket should be seen listed with existing tickets

----

*Credentials*: Unstoppable_CR

----

*Reproduction Steps*:
Logged in as a regular user and on games page
Click on profile icon and select my tickets
Afterwards, click on new ticket button
Enter all details and add image
Click on create  ticket button

*Attached Files*:
https://tracker-production.gatserver.com/video_files/c207283a3916852d6c94a83a0e05d37cfe52ac60386ec8e7e3ce2a96731af9ac287207398d21629d7984b849c2e8786b

**Comment by ChalkyBrush** [comment]
#36
