### ISSUE TITLE
[GAT-MEW002-53][Windows][IE11(11.0.9600.17843)] Nothing happens when clicking on "Select File" option during support ticket raising

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#36]
*Issue No*: 53
*Device*: Sony Ericsson Windows Phone 7, Windows 7
*Web Browser*: IE11(11.0.9600.17843)

*Affected Component(s)*:
* Regular user

----

*Bug Description*:
Actual results
Nothing is happening and no pop up or dialog box is opened to choose a file

Expected results
Browse a file window should be opened to choose a file

----

*Credentials*: regular User: Trainer_Asian

----

*Reproduction Steps*:
Logged in as a regular user 
Tap on Support Tickets , then tap on New Ticket. New Support ticket compose window should be opened
Choose category and enter subject as well as enter some details in details section
Tap on "Select File" button and check the behavior

*Attached Files*:
https://tracker-production.gatserver.com/video_files/785f24a50fc4c6cb5d7a088643785427f10211124edc793ce8a9b6dfb2eb80d07240e66c26d6d689859bed342244a268

**Comment by ChalkyBrush** [comment]
fixed!
