### ISSUE TITLE
[GAT-MEW002-7][Windows][Chrome 64] Clicking on "Pro Shop" link take user to an error page

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#4]
*Issue No*: 7
*Device*: Huawei P9, Windows 10
*Web Browser*: Chrome 64

*Affected Component(s)*:
* Admin console

----

*Bug Description*:
Actual results
Clicking on "Pro Shop" link from the bottom of the page leads to a 404 error page.

Expected results
Clicking on "Pro Shop" link from the bottom of the page should take the user to an appropriate page.

----

*Credentials*: test_adm7

----

*Reproduction Steps*:
Browse to "http://stage.millennialesports.gg/"
Login as admin
Scroll down to bottom of the page
Click on Pro shop
Observe

*Attached Files*:
https://tracker-production.gatserver.com/video_files/3de0d1b4a5457b9f999c94bb42dcbbb936a15c010e71d985a3f84eea81cfc7dd7f8a39efcf14148178f2089cc4d7a711

**Comment by ChalkyBrush** [comment]
fixed
