### ISSUE TITLE
[GAT-MEW002-65][Windows][IE 11] An error is displayed when clicking on 'Save and add another' twice.

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#43]
*Issue No*: 65
*Device*: Apple iPhone 6S, Windows 10
*Web Browser*: IE 11

*Affected Component(s)*:
* Admin console

----

*Bug Description*:
Actual results
In the 'New Team user' page, click on 'Save and add another' twice, then the system displays 'Something went terribly wrong:500 error'.

Expected results
In the 'New Team user' page, click on 'Save and add another' twice, then the system save current team user and create new team user successfully without any error

----

*Credentials*: test_adm15

----

*Reproduction Steps*:
Go to http://stage.millennialesports.gg/
Log in as admin
Click on 'Team users'
Click on 'Edit' button
Click on 'Save and add another' twice

*Attached Files*:
https://tracker-production.gatserver.com/video_files/0256ec13f36991461da4caca1bf609685d08acc7841915e1acffe49e555cb113c99244460c956d8045a789c5ecf4793c

**Comment by ChalkyBrush** [comment]
removed team users from admin console
