### ISSUE TITLE
[GAT-MEW002-74][Windows][IE11] Clicking on "here" link from "Register a new team" pop up for Clash Royale CS Cup #8 - $150 taken to 404 error page

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#51]
*Issue No*: 74
*Device*: Sony Ericsson Windows Phone 7, Windows 10
*Web Browser*: IE11 (version 11.0.9600.17843)

*Affected Component(s)*:
* Regular user

----

*Bug Description*:
Actual results
User is being taken to 404 error page.

Expected results
Respective page should be opened

----

*Credentials*: Regular User: Trainer_Asian

----

*Reproduction Steps*:
Open IE11 browser and enter test url > Login as a regular user
Tap on Tournaments 
Under All games tap on "Clash Royale CS Cup #8 - $150 " 
Tap on Register a New Team button
From the opened popup tap on "here" link
Check the behavior

*Attached Files*:
https://tracker-production.gatserver.com/video_files/5fb0aedeed9d87abd0d87023d8bc4fb3ec8f83fa870d2d4b8b27a8a41063317790291020e148274409ab6b7ac77b2faf

**Comment by ChalkyBrush** [comment]
Fixed!
