### ISSUE TITLE
[GAT-MEW002-77][Windows][Google Chrome Version 64] Email and Password field on the "Add New User" form are marked as optional but they are actually required

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#52]
*Issue No*: 77
*Device*: Xiaomi Redmi 4a, Windows 10
*Web Browser*: Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)

*Affected Component(s)*:
* Admin console

----

*Bug Description*:
Actual results
On the admin console, the user opens the "Teams" menu and edit a certain team. On the "Users" section, try to add a new user. When the new user form popping up, notice that Email and Password field are marked as optional but they are actually required.

Expected results
The form validation and the field information (required/optional) should match.

----

*Credentials*: test_adm3

----

*Reproduction Steps*:
Open the admin console (http://stage.millennialesports.gg/admin/)
Proceed to "Teams" menu
Edit a team
Add a new user
Notice that Email and Password field are marked as optional but they are actually required.

*Attached Files*:
https://tracker-production.gatserver.com/video_files/2295c4b4efe5166f686c2c6f1101921b1d466e6f4f96212f0a9f55258eb069fab2ed75bed6dd90522485c8aee80582f5

**Comment by ChalkyBrush** [comment]
not adding users from admin console
