### ISSUE TITLE
[GAT-MEW002-89][Windows][Google Chrome 64] Log in works as a button, not as an info text

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#55]
*Issue No*: 89
*Device*: Huawei P9 Lite, Windows 10
*Web Browser*: Google Chrome is up to date Version 64.0.3282.167 (Official Build) (64-bit)

*Affected Component(s)*:
* Regular user

----

*Bug Description*:
Actual results
Log in is a button. All other text above  (Lifetime Earnings: $0 Total Matches: 0 Total Wins: 0 Account Age: 11 days) are for info purposes.

Expected results
All texts should be for info purposes. "Log in as" should not be a button placed there.

----

*Credentials*: Fetusjr

----

*Reproduction Steps*:
open the web and log in as regular user
click on wiev full profile button on the center of the screen
observe information about Lifetime Earnings: $0 Total Matches: 0 Total Wins: 0 Account Age: 11 days
observe "Log in as" is a button placed under info text

*Attached Files*:
https://tracker-production.gatserver.com/image_files/69969423c106539b8e65d6d8c276dd8d002d016b625f47d880f67c8838c65ce332d4cbd75fcbb992c1c1fdfd4bb3402d
https://tracker-production.gatserver.com/video_files/31e53190ab345f9d0a33d11e605a4e00f6f30a25fc7c7c792e3ec8ce2b83f80d252719191523f3f5b8682a2c453cee7b

**Comment by ChalkyBrush** [comment]
made into a button and clarified text
<img width="1061" alt="screen shot 2018-02-22 at 10 54 08 am" src="https://user-images.githubusercontent.com/5232984/36548628-cc3b98ae-17be-11e8-8635-16094cd7d315.png">
