### ISSUE TITLE
[GAT-MEW002-91][Windows][Firefox 58] Admin cannot add a new user due to age restriction

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#56]
*Issue No*: 91
*Device*: Huawei P9 Lite, Windows 10
*Web Browser*: firefox 58.0.2
*Affected Component(s)*:
* Admin console

----

*Bug Description*:
Actual results
User failed to be added. A red message is displayed - Sorry, but you must be at least 13 years or older to register! . Date of birth for the admin is 26 nov 1990.

Expected results
Admin should be able to add a new user

----

*Credentials*: test_adm16

----

*Reproduction Steps*:
open stage.millennialesports.gg/users/USERNAME/become
replace USERNAME with test_adm16
click profile picture on top right corner
click edit account on the opened menu/observe the date of birth
on the url http://stage.millennialesports.gg/ type /admin and enter
on the new page click users in the left menu
click add new
fill in the fields with a username, an email, a password
click save/observe the top red message

*Attached Files*:
https://tracker-production.gatserver.com/video_files/e804efdf3d6e238a3568d064f31495336c05eb9d347eb0c639826345960d1e9e0cd427a31c2565f20036a4374d6a0694

**Comment by ChalkyBrush** [comment]
shouldn't be adding users from admin console 😈
