### ISSUE TITLE
[GAT-MEW002-92][Windows][Firefox 58] No warning message for a user added with an invalid email, with no domain

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#57]
*Issue No*: 92
*Device*: Huawei P9 Lite, Windows 10
*Web Browser*: firefox 58.0.2 

*Affected Component(s)*:
* Admin console

----

*Bug Description*:
Actual results
An invalid email with no domain e.g gfgdsg@fs can be set for a user to be added by admin

Expected results
Should be a warning message for the invalid email with no domain

----

*Credentials*: test_adm16

----

*Reproduction Steps*:
open stage.millennialesports.gg/users/USERNAME/become
 replace USERNAME with test_adm16
on the url http://stage.millennialesports.gg/ type /admin and enter
on the new page click users in the left menu
 click add new
fill in the fileds: username, email with an invalid email with false domain, password 
click save
no warning message

*Attached Files*:
https://tracker-production.gatserver.com/video_files/eca7a665461185a8e77174f25a62c457233a3dcf7158052cb0702826104a0d0d221742648cde60a06240ea4433867a1a

**Comment by ChalkyBrush** [comment]
adding users from admin console is not a critical function
