### ISSUE TITLE
[GAT-MEW002-95][Windows][Google Chrome Version 64.0.3282.167] "Save and edit" for "New Team user" gives error

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#58]
*Issue No*: 95
*Device*: Samsung Galaxy S6, Windows 10
*Web Browser*: Google Chrome Version 64.0.3282.167

*Affected Component(s)*:
* Admin console

----

*Bug Description*:
Actual results
When you click "Save and edit" when adding a new team user, you get the error "SOMETHING WENT TERRIBLY WRONG: 500 ERROR".

Expected results
There should not be an error message. You should be able to add the new team user without any issue.

----

*Credentials*: test_adm25

----

*Reproduction Steps*:
Log in as admin test_adm25
Click Team users
Click Add New
Select whichever checkboxes you want
Click "Save and edit"
See error

*Attached Files*:
https://tracker-production.gatserver.com/video_files/7164152a5df6f375f03b3e431460b590b97d27b0299a68562930b27a61ec9f3eaaaf083bed79f9a5441f9e1b78c23248

**Comment by ChalkyBrush** [comment]
Actually you shouldn't be able to add team users from this panel. Team users are added on the main team console page.

To improve this we removed Team Users from the sidebar
