### ISSUE TITLE
[GAT-MEW002-97][Windows][firefox58.0.2] The admin is not able to send a message to his team

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#59]
*Issue No*: 97
*Device*: Huawei P9 Lite, Windows 10
*Web Browser*: firefox58.0.2 

*Affected Component(s)*:
* Admin console

----

*Bug Description*:
Actual results
Message team tab cannot be fill in with messages

Expected results
In the tab "Message team", the user should be able to write and send a message

----

*Credentials*: test_adm16

----

*Reproduction Steps*:
open stage.millennialesports.gg/users/USERNAME/become 
log in as admin
in theURL http://stage.millennialesports.gg/ type /admin and enter
scroll down and click Teams button
on a asasas created team click on speaking-tube icon
observe the new message team tab

*Attached Files*:
https://tracker-production.gatserver.com/video_files/2bbf7cc9c049b3275e7329fd561ea8c8efe6aca2036be51d2f477b12172fa159a14e5be3f1be139eef069b93841b998e

**Comment by ChalkyBrush** [comment]
message team was moved to the regular UI
