### ISSUE TITLE
[GAT-MEW002-98][Windows][Internet Explorer 11] No feedback displayed when clicking Submit in the 'Contact Us' form.

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#60]
*Issue No*: 98
*Device*: Windows 10
*Web Browser*: Internet Explorer 11

*Affected Component(s)*:
* Admin console

----

*Bug Description*:
Actual results
The submit function failed to send information after entering data in the required fields.  The page jumps to the beginning/top of the page.

Expected results
Expected to submit the form upon completion.

----

*Credentials*: pgl, beta2014 (test_adm17)

----

*Reproduction Steps*:
Go to: http://stage.millennialesports.gg/contact
Enter: Tester Name > email > subject > category > phone# > country > request
Select: Submit

*Attached Files*:
https://tracker-production.gatserver.com/video_files/d674391172d1d870b9d901007b50865b28e06fbd80aa982a3fe227f80d1dc1d5dba0c846edeacdcf58c7be528e302106

**Comment by ChalkyBrush** [comment]
seems to be a problem on stage only
