### ISSUE TITLE
[GAT-MEW002-100][Windows][Chrome Version 64.0.3282.167] Unable to remove a pending friend request, clicking the 'Remove' button will trigger the 'add friend' function

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#61]
*Issue No*: 100
*Device*: HTC One (M8) for Windows, Windows 7
*Web Browser*: Chrome Version 64.0.3282.167

*Affected Component(s)*:
* Regular user

----

*Bug Description*:
Actual results
When you request to 'add a friend' on a user, removing it on the pending request list will trigger the add function

Expected results
Clicking the 'Remove' button should open the function to completely remove the user on the list

----

*Credentials*: stage.millennialesports.gg/users/LordTG/become

----

*Reproduction Steps*:
Use the link:  stage.millennialesports.gg/users/LordTG/become
Precondition: Add a user as a friend, to put the user on the pending list
Click on the 'Friend' button at the top right side of the page
Drag the mouse on the pending friend request then click the 'Cancel' button. Observe

*Attached Files*:
https://tracker-production.gatserver.com/video_files/f36c43ee8289bcf5c314a67056772f87d47f4c8aa355125d56c535243596b01284bf6e5bd30ced8b10fc506e71f3f973

**Comment by ChalkyBrush** [comment]
good find, fixed
