### ISSUE TITLE
[GAT-MEW002-11][OS X][chrome 64] Unable to send message to all the team members from an admin panel

### ISSUE THREAD

**Issue by gatgithub** [progamingleague/gg-bug-tracker#8]
*Issue No*: 11
*Device*: Apple iPhone 8 Plus, OS X 10.10 Yosemite
*Web Browser*: chrome 64

*Affected Component(s)*:
* Admin dashboard

----

*Bug Description*:
Actual results
I have created a team but when I am sending a message than error page is shown

Expected results
If there are no team members than proper error message should be shown. And if there are team members than error message should be sent successfully.

----

*Credentials*: stage.millennialesports.gg/users/test_adm19/become 

----

*Reproduction Steps*:
Go to this link: stage.millennialesports.gg/users/test_adm19/become  
Click Tournaments
Click the cup panel with prize and team
Click Public profile
Click Admin:Message team
Enter message 
Click send and observe

*Attached Files*:
https://tracker-production.gatserver.com/video_files/c3665687c9136a95724bc24479611de1375a772ff7be95fee43d111295e798c5846f73c8baed5fa9d0b23214da8defb9

**Comment by ChalkyBrush** [comment]
removed functionality (shows up on main UI)
